export const VN = [
  "Hà Nội (HAN)",
  "Hồ Chí Minh (SGN)",
  "Đà Nẵng (DAD)",
  "Điện Biên Phủ",
  "Hải Phòng (HPH)",
  "Thanh Hóa (THD)",
  "Vinh (VII)",
  "Quảng Bình (VDH)",
  "Quảng Nam (VCL)",
  "Huế (HUI)",
  "PleiKu (PXU)",
  "Phú Yên (TBB)",
  "Ban Mê Thuột (BMV)",
  "Nha Trang (CXR)",
  "Qui Nhơn (UIH)",
  "Đà Lạt (DLI)",
  "Cần Thơ (VCA)",
  "Phú Quốc (PQC)",
  "Côn Đảo (VCS)",
  "Vân Đồn (VDO)",
];

export const ChauA = [
  {
    name: "Đông dương",
    children: [
      "Phnôm Pênh (PNH)",
      "Siem Reap (REP)",
      "Viên Chăn (VTE)",
      "Luông pra băng (LPQ)",
    ],
  },
  {
    name: "Đông Nam Á ",
    children: [
      "Jakarta (JKT)",
      "Băng Cốc (BKK)",
      "Bali Denpasar (DPS)",
      "Kuala Lumpur (KUL)",
      "Manila (MNL)",
      "Singapore (SIN)",
      "Yangon (RGN)",
    ],
  },
  {
    name: "Đông Bắc Á",
    children: [
      "Bắc Kinh (BJS)",
      "Bắc Kinh (PEK)",
      "Thượng Hải (PVG)",
      "Thượng Hải (SHA)",
      "Quảng Châu (CAN)",
      "Đài Bắc (TPE)",
      "Đài Trung (RMQ)",
      "Cao Hùng (KHH)",
      "Đài Nam (TNN)",
      "Hồng Kông (HKG)",
      "Tokyo (NRT)",
      "Tokyo (HND)",
      "Nagoya (NGO)",
      "Fukuoka (FUK)",
      "Osaka (OSA)",
      "Osaka (KIX)",
      "Seoul (ICN)",
      " Seoul (SEL)",
      "Pusan (PUS)",
    ],
  },
  {
    name: "Tây Á",
    children: [
      "Mumbai (BOM)",
      "Đê-li (DEL)",
      "Kathmandu (KTM)",
      "Dhaka (DAC)",
      "Colombo (CMB)",
      "Kolkata (CCU)",
      "Istanbul (IST)",
      "Dubai (DXB)",
    ],
  },
];

export const ChauAu = [
  "Paris (CDG)",
  "Luân Đôn (LON)",
  "Manchester (MAN)",
  "Berlin (TXL)",
  "Frankfurt (FRA)",
  "Amsterdam (AMS)",
  "Madrid (MAD)",
  "Mát-xờ-cơ-va (MOW)",
  "Geneva (GVA)",
  "Praha (PRG)",
  "Rome (ROM)",
  "Viên (VIE)",
  "Cô-pen-ha-gen (CPH)",
];

export const HoaKy = [
  "New York (NYC)",
  "New York (JFK)",
  "Washington (WAS)",
  "Los Angeles (LAX)",
  "San Francisco (SFO)",
  "Los Angeles (LAX)",
  "Atlanta (ALT)",
  "Boston (BOS)",
  "Chicago (CHI)",
  "Dallas (DFW)",
  "Denver (DEN)",
  "Honolulu (HNL)",
  "Miami (MIA)",
  "Minneapolis (MSP)",
  "Philadelphia (PHL)",
  "Portland (Oregon) (PDX)",
  "Seattle (SEA)",
  "St Louis (STL)",
  "Vancouver (YVR)",
  "Toronto (YYZ)",
  "Ottawa (YOW)",
  "Montreal (YMQ)",
];

export const ChauUc = [
  {
    name: "Châu Úc",
    children: [
      "Men-bơn (MEL)",
      "Sydney (SYD)",
      "Adelaide (ADL)",
      "Brisbane (BNE)",
      "Brisbane (Auckland)",
      "Wellington (WLG)",
    ],
  },
  {
    name: "Châu Phi",
    children: [
      "Nairobi (NBO)",
      "Maputo (MPM)",
      "Luanda (LAD)",
      "Johannesburg (JNB)",
      "Cape Town (CPT)",
      "Dar Es Salaam (DAR)",
    ],
  },
];
